[tool.poetry]
name = "agent-protocol-client"
version = "1.0.0"
description = "Agent Communication Protocol Client"
authors = ["AI Engineers Foundation <aiengineersfoundation@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://agentprotocol.ai/"
repository = "https://github.com/AI-Engineers-Foundation/agent-protocol/tree/main/packages/client/python"
packages = [{ include = "agent_protocol_client" }]

[tool.poetry.dependencies]
python = "^3.10"

urllib3 = ">= 1.25.3"
python-dateutil = ">=2.8.2"
aiohttp = ">= 3.8.4"
pydantic = "^1.10.5, <2"
aenum = ">=3.1.11"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/AI-Engineers-Foundation/agent-protocol/issues"
