name: Convert OpenAPI

on:
  push:
    paths:
      - 'schemas/openapi.yml'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install swagger-cli
      run: npm install -g swagger-cli

    - name: Convert openapi.yml to openapi.json
      run: |
        swagger-cli bundle -r schemas/openapi.yml -o schemas/openapi.json -t json
        cp schemas/openapi.yml openapi.yml
        cp schemas/openapi.json openapi.json

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add schemas/openapi.json
        git add openapi.yml
        git add openapi.json
        git commit -m "Update openapi files" || echo "No changes to commit"
        git push
